name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build, and test
        run: |
          npm install
          npm run build:prod
          npm run build-cjs
          chmod +x ./dist-bundled/*
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-bundled
          path: |
            dist-bundled
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
      - name: Upload binaries to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist-bundled/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true